Initial Testing
It seems like the testing is going alright... The AI has learned to walk on it's knees to maximize the foot_clearance reward. I made some immediate changes to value track_foot_clearance less. Also, the training crashed after 225 iterations because somehow there was an NaN value in either the observations or the actions... Error:
```
isaaclab311/lib/python3.11/site-packages/torch/distributions/normal.py", line 74, in sample
    return torch.normal(self.loc.expand(shape), self.scale.expand(shape))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: normal expects all elements of std >= 0.0
```

Two things TODO:
1. Add a non-foot-contact-penalty so only the feet can touch the ground.
2. Find out why the error is happening and debug it. Maybe add some error catchers to the observation manager to try and catch it. It might mean one of our observations is sometimes garbage.

Co-Authored-By: Adam Gans <130410191+AdamTheGans@users.noreply.github.com>